/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.iot.kafka.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MqttMockAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1693729468722067191L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MqttMockAvroModel\",\"namespace\":\"com.iot.kafka.avro.model\",\"fields\":[{\"name\":\"deviceId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"timestamp\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"metricType\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"value\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"unit\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"status\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"batteryLevel\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"location\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MqttMockAvroModel> ENCODER =
      new BinaryMessageEncoder<MqttMockAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MqttMockAvroModel> DECODER =
      new BinaryMessageDecoder<MqttMockAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MqttMockAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MqttMockAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MqttMockAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MqttMockAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MqttMockAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MqttMockAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MqttMockAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MqttMockAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String deviceId;
   private long timestamp;
   private java.lang.String metricType;
   private java.lang.Double value;
   private java.lang.String unit;
   private java.lang.String status;
   private java.lang.Integer batteryLevel;
   private java.lang.String location;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MqttMockAvroModel() {}

  /**
   * All-args constructor.
   * @param deviceId The new value for deviceId
   * @param timestamp The new value for timestamp
   * @param metricType The new value for metricType
   * @param value The new value for value
   * @param unit The new value for unit
   * @param status The new value for status
   * @param batteryLevel The new value for batteryLevel
   * @param location The new value for location
   */
  public MqttMockAvroModel(java.lang.String deviceId, java.lang.Long timestamp, java.lang.String metricType, java.lang.Double value, java.lang.String unit, java.lang.String status, java.lang.Integer batteryLevel, java.lang.String location) {
    this.deviceId = deviceId;
    this.timestamp = timestamp;
    this.metricType = metricType;
    this.value = value;
    this.unit = unit;
    this.status = status;
    this.batteryLevel = batteryLevel;
    this.location = location;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return deviceId;
    case 1: return timestamp;
    case 2: return metricType;
    case 3: return value;
    case 4: return unit;
    case 5: return status;
    case 6: return batteryLevel;
    case 7: return location;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: deviceId = value$ != null ? value$.toString() : null; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: metricType = value$ != null ? value$.toString() : null; break;
    case 3: value = (java.lang.Double)value$; break;
    case 4: unit = value$ != null ? value$.toString() : null; break;
    case 5: status = value$ != null ? value$.toString() : null; break;
    case 6: batteryLevel = (java.lang.Integer)value$; break;
    case 7: location = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'deviceId' field.
   * @return The value of the 'deviceId' field.
   */
  public java.lang.String getDeviceId() {
    return deviceId;
  }


  /**
   * Sets the value of the 'deviceId' field.
   * @param value the value to set.
   */
  public void setDeviceId(java.lang.String value) {
    this.deviceId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'metricType' field.
   * @return The value of the 'metricType' field.
   */
  public java.lang.String getMetricType() {
    return metricType;
  }


  /**
   * Sets the value of the 'metricType' field.
   * @param value the value to set.
   */
  public void setMetricType(java.lang.String value) {
    this.metricType = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public java.lang.Double getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.Double value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'unit' field.
   * @return The value of the 'unit' field.
   */
  public java.lang.String getUnit() {
    return unit;
  }


  /**
   * Sets the value of the 'unit' field.
   * @param value the value to set.
   */
  public void setUnit(java.lang.String value) {
    this.unit = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.String getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.String value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'batteryLevel' field.
   * @return The value of the 'batteryLevel' field.
   */
  public java.lang.Integer getBatteryLevel() {
    return batteryLevel;
  }


  /**
   * Sets the value of the 'batteryLevel' field.
   * @param value the value to set.
   */
  public void setBatteryLevel(java.lang.Integer value) {
    this.batteryLevel = value;
  }

  /**
   * Gets the value of the 'location' field.
   * @return The value of the 'location' field.
   */
  public java.lang.String getLocation() {
    return location;
  }


  /**
   * Sets the value of the 'location' field.
   * @param value the value to set.
   */
  public void setLocation(java.lang.String value) {
    this.location = value;
  }

  /**
   * Creates a new MqttMockAvroModel RecordBuilder.
   * @return A new MqttMockAvroModel RecordBuilder
   */
  public static com.iot.kafka.avro.model.MqttMockAvroModel.Builder newBuilder() {
    return new com.iot.kafka.avro.model.MqttMockAvroModel.Builder();
  }

  /**
   * Creates a new MqttMockAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MqttMockAvroModel RecordBuilder
   */
  public static com.iot.kafka.avro.model.MqttMockAvroModel.Builder newBuilder(com.iot.kafka.avro.model.MqttMockAvroModel.Builder other) {
    if (other == null) {
      return new com.iot.kafka.avro.model.MqttMockAvroModel.Builder();
    } else {
      return new com.iot.kafka.avro.model.MqttMockAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new MqttMockAvroModel RecordBuilder by copying an existing MqttMockAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new MqttMockAvroModel RecordBuilder
   */
  public static com.iot.kafka.avro.model.MqttMockAvroModel.Builder newBuilder(com.iot.kafka.avro.model.MqttMockAvroModel other) {
    if (other == null) {
      return new com.iot.kafka.avro.model.MqttMockAvroModel.Builder();
    } else {
      return new com.iot.kafka.avro.model.MqttMockAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for MqttMockAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MqttMockAvroModel>
    implements org.apache.avro.data.RecordBuilder<MqttMockAvroModel> {

    private java.lang.String deviceId;
    private long timestamp;
    private java.lang.String metricType;
    private java.lang.Double value;
    private java.lang.String unit;
    private java.lang.String status;
    private java.lang.Integer batteryLevel;
    private java.lang.String location;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.iot.kafka.avro.model.MqttMockAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.deviceId)) {
        this.deviceId = data().deepCopy(fields()[0].schema(), other.deviceId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.metricType)) {
        this.metricType = data().deepCopy(fields()[2].schema(), other.metricType);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.value)) {
        this.value = data().deepCopy(fields()[3].schema(), other.value);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.unit)) {
        this.unit = data().deepCopy(fields()[4].schema(), other.unit);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.batteryLevel)) {
        this.batteryLevel = data().deepCopy(fields()[6].schema(), other.batteryLevel);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.location)) {
        this.location = data().deepCopy(fields()[7].schema(), other.location);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing MqttMockAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.iot.kafka.avro.model.MqttMockAvroModel other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.deviceId)) {
        this.deviceId = data().deepCopy(fields()[0].schema(), other.deviceId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.metricType)) {
        this.metricType = data().deepCopy(fields()[2].schema(), other.metricType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.value)) {
        this.value = data().deepCopy(fields()[3].schema(), other.value);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.unit)) {
        this.unit = data().deepCopy(fields()[4].schema(), other.unit);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.batteryLevel)) {
        this.batteryLevel = data().deepCopy(fields()[6].schema(), other.batteryLevel);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.location)) {
        this.location = data().deepCopy(fields()[7].schema(), other.location);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'deviceId' field.
      * @return The value.
      */
    public java.lang.String getDeviceId() {
      return deviceId;
    }


    /**
      * Sets the value of the 'deviceId' field.
      * @param value The value of 'deviceId'.
      * @return This builder.
      */
    public com.iot.kafka.avro.model.MqttMockAvroModel.Builder setDeviceId(java.lang.String value) {
      validate(fields()[0], value);
      this.deviceId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'deviceId' field has been set.
      * @return True if the 'deviceId' field has been set, false otherwise.
      */
    public boolean hasDeviceId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'deviceId' field.
      * @return This builder.
      */
    public com.iot.kafka.avro.model.MqttMockAvroModel.Builder clearDeviceId() {
      deviceId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.iot.kafka.avro.model.MqttMockAvroModel.Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.iot.kafka.avro.model.MqttMockAvroModel.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'metricType' field.
      * @return The value.
      */
    public java.lang.String getMetricType() {
      return metricType;
    }


    /**
      * Sets the value of the 'metricType' field.
      * @param value The value of 'metricType'.
      * @return This builder.
      */
    public com.iot.kafka.avro.model.MqttMockAvroModel.Builder setMetricType(java.lang.String value) {
      validate(fields()[2], value);
      this.metricType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'metricType' field has been set.
      * @return True if the 'metricType' field has been set, false otherwise.
      */
    public boolean hasMetricType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'metricType' field.
      * @return This builder.
      */
    public com.iot.kafka.avro.model.MqttMockAvroModel.Builder clearMetricType() {
      metricType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.lang.Double getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public com.iot.kafka.avro.model.MqttMockAvroModel.Builder setValue(java.lang.Double value) {
      validate(fields()[3], value);
      this.value = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public com.iot.kafka.avro.model.MqttMockAvroModel.Builder clearValue() {
      value = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'unit' field.
      * @return The value.
      */
    public java.lang.String getUnit() {
      return unit;
    }


    /**
      * Sets the value of the 'unit' field.
      * @param value The value of 'unit'.
      * @return This builder.
      */
    public com.iot.kafka.avro.model.MqttMockAvroModel.Builder setUnit(java.lang.String value) {
      validate(fields()[4], value);
      this.unit = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'unit' field has been set.
      * @return True if the 'unit' field has been set, false otherwise.
      */
    public boolean hasUnit() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'unit' field.
      * @return This builder.
      */
    public com.iot.kafka.avro.model.MqttMockAvroModel.Builder clearUnit() {
      unit = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.String getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.iot.kafka.avro.model.MqttMockAvroModel.Builder setStatus(java.lang.String value) {
      validate(fields()[5], value);
      this.status = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.iot.kafka.avro.model.MqttMockAvroModel.Builder clearStatus() {
      status = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'batteryLevel' field.
      * @return The value.
      */
    public java.lang.Integer getBatteryLevel() {
      return batteryLevel;
    }


    /**
      * Sets the value of the 'batteryLevel' field.
      * @param value The value of 'batteryLevel'.
      * @return This builder.
      */
    public com.iot.kafka.avro.model.MqttMockAvroModel.Builder setBatteryLevel(java.lang.Integer value) {
      validate(fields()[6], value);
      this.batteryLevel = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'batteryLevel' field has been set.
      * @return True if the 'batteryLevel' field has been set, false otherwise.
      */
    public boolean hasBatteryLevel() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'batteryLevel' field.
      * @return This builder.
      */
    public com.iot.kafka.avro.model.MqttMockAvroModel.Builder clearBatteryLevel() {
      batteryLevel = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'location' field.
      * @return The value.
      */
    public java.lang.String getLocation() {
      return location;
    }


    /**
      * Sets the value of the 'location' field.
      * @param value The value of 'location'.
      * @return This builder.
      */
    public com.iot.kafka.avro.model.MqttMockAvroModel.Builder setLocation(java.lang.String value) {
      validate(fields()[7], value);
      this.location = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'location' field has been set.
      * @return True if the 'location' field has been set, false otherwise.
      */
    public boolean hasLocation() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'location' field.
      * @return This builder.
      */
    public com.iot.kafka.avro.model.MqttMockAvroModel.Builder clearLocation() {
      location = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MqttMockAvroModel build() {
      try {
        MqttMockAvroModel record = new MqttMockAvroModel();
        record.deviceId = fieldSetFlags()[0] ? this.deviceId : (java.lang.String) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        record.metricType = fieldSetFlags()[2] ? this.metricType : (java.lang.String) defaultValue(fields()[2]);
        record.value = fieldSetFlags()[3] ? this.value : (java.lang.Double) defaultValue(fields()[3]);
        record.unit = fieldSetFlags()[4] ? this.unit : (java.lang.String) defaultValue(fields()[4]);
        record.status = fieldSetFlags()[5] ? this.status : (java.lang.String) defaultValue(fields()[5]);
        record.batteryLevel = fieldSetFlags()[6] ? this.batteryLevel : (java.lang.Integer) defaultValue(fields()[6]);
        record.location = fieldSetFlags()[7] ? this.location : (java.lang.String) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MqttMockAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<MqttMockAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MqttMockAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<MqttMockAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.deviceId);

    out.writeLong(this.timestamp);

    if (this.metricType == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.metricType);
    }

    if (this.value == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.value);
    }

    if (this.unit == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.unit);
    }

    if (this.status == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.status);
    }

    if (this.batteryLevel == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.batteryLevel);
    }

    if (this.location == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.location);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.deviceId = in.readString();

      this.timestamp = in.readLong();

      if (in.readIndex() != 1) {
        in.readNull();
        this.metricType = null;
      } else {
        this.metricType = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.value = null;
      } else {
        this.value = in.readDouble();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.unit = null;
      } else {
        this.unit = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.status = null;
      } else {
        this.status = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.batteryLevel = null;
      } else {
        this.batteryLevel = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.location = null;
      } else {
        this.location = in.readString();
      }

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.deviceId = in.readString();
          break;

        case 1:
          this.timestamp = in.readLong();
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.metricType = null;
          } else {
            this.metricType = in.readString();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.value = null;
          } else {
            this.value = in.readDouble();
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.unit = null;
          } else {
            this.unit = in.readString();
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.status = null;
          } else {
            this.status = in.readString();
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.batteryLevel = null;
          } else {
            this.batteryLevel = in.readInt();
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.location = null;
          } else {
            this.location = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










